### ISSUE TITLE
Is this some kind of a joke?

### ISSUE THREAD

**Issue by Andrewsville** [QuantiCZ/MailQ-PHP-Library#1]
We are using MailQ and wanted to stop using it manually a start using it automatically, starting with a couple of Symfony Commands that would accomplish basic tasks. And this is how it went.

I've added the library to our app composer dependencies (version 0.2.0 that matches current master).

I started with the recipient lists list. I've called `$mailQ->getRecipientsLists` and got a strict warning about `Request::createRequest()` being called statically when not being static. OK, I've made it static. BTW Do you really develop with strict warnings turned off? 

Then I got a fatal error because class `Response` didn't exist. Well, it really didn't. So I [fixed it](https://github.com/QuantiCZ/MailQ-PHP-Library/blob/master/src/MailQ/Connector.php#L69).

Then I got an error that "292 is not a curl resource" (or something like that). Well, I [fixed it](https://github.com/QuantiCZ/MailQ-PHP-Library/blob/master/src/MailQ/Connector.php#L58). You can't really [close a curl resource](https://github.com/QuantiCZ/MailQ-PHP-Library/blob/master/src/MailQ/Connector.php#L58) and [try to use it later](https://github.com/QuantiCZ/MailQ-PHP-Library/blob/master/src/MailQ/Connector.php#L70) (try to close a database connection and use it later and see how that goes).

Then I tried to list recipients lists that I am member of. And strangely, it returned the same list all the time. [Guess why](https://github.com/QuantiCZ/MailQ-PHP-Library/blob/master/src/MailQ/Connector.php#L42). Yes, because you prepare a cool `$url` variable (there should be a `.=` [here](https://github.com/QuantiCZ/MailQ-PHP-Library/blob/master/src/MailQ/Connector.php#L40) btw) but you don't use it and build the request URL again.

I fixed that and got a correct list.

Then I tried to create a new recipients list. And a cute little thing happened. When I didn't provide the "variables" parameter, your service crashed:

> {"error":{"message":"Cannot invoke method asList() on null object","note":"This exception was not expected. Please send error message to developers."}}

I kinda expected that when I don't pass an explicit value to `ResponseListEntity` constructor, it will use a default value (empty array I would guess). Well, I was wrong. OK, I started to provide at least an empty array/object.

Then I tried to delete the recipient list. And I have to admit, I was surprised it had worked.

Then I tried to list members of a recipient list. And for some reason a [RecipientEntity is returned instead of a RecipientsEntity](https://github.com/QuantiCZ/MailQ-PHP-Library/blob/master/src/MailQ/Resources/RecipientListResource.php#L125). So I tried to fix it. And I obviously had to use that [cute tweak](https://github.com/QuantiCZ/MailQ-PHP-Library/blob/master/src/MailQ/Resources/RecipientListResource.php#L164) to make a `data` parameter a `recipients` parameter.

And it started working. Kinda. Recipients didn't get their email into the `email` property but it was inside the `data` property.

And that's where I've decided to use all my powers to make our project stop using MailQ and migrate somewhere else.

**Comment by blazekv** [comment]
I am sorry, that you have terrible first experience with library. We moved our library from private repository to GitHub, but it does it mean it is ready for production use (you could see it from version number which is not 1.0.0 but still 0.2.5). I fixed all bug you mention in your post.
