### ISSUE TITLE
Entity annotations parsing does not work

### ISSUE THREAD

**Issue by Andrewsville** [QuantiCZ/MailQ-PHP-Library#7]
We are still facing the notice when trying to parse annotations that @dominikdvoracek reported. Upgrading to 0.7.0 did not help.

![shot_170331_121353](https://cloud.githubusercontent.com/assets/506715/24546507/e00c59be-160b-11e7-9315-5a022730d573.png)

The problem is that you assume that `$property->getAnnotation($mapping);` returns an Annotation object. However it does not despite the method's docblock claiming [it does](https://github.com/nette/reflection/blob/master/src/Reflection/Property.php#L69). In fact when this notice is raised `$annotation` contains a string `"undeliveredTimestamp"`.

I suppose it used to work but stopped when [this PR](https://github.com/nette/reflection/pull/2) was [merged to Nette\Reflection](https://github.com/nette/reflection/commit/cf33b9c23aebff3bf33067f4e8e5ea64c576f234).

**Comment by Andrewsville** [comment]
Bottom line - having requirements like "2.*" for anything Nette-related is a Really Bad Idea™.
Thanks to how Nette versioning works the difference between 2.x and 2.x+1 is like 2 and 3 in normal development :)

**Comment by blazekv** [comment]
I could not reproduce it. But I tried to fix it. Could you please verify it works? What is your Nette version I tried the last one and it worked.

Thanks for your advice. I locked Nette libraries to version 2.4.x.
